import Link from 'next/link';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { requireAccount } from '@/lib/supabase/session';
import SubmitButton from '@/components/auth/SubmitButton';
import { addServiceInstance, moderateReview, updateServiceRequest } from './actions';
import { services } from '@/data/services';
export const dynamic = 'force-dynamic';
export const metadata: Metadata = { title: 'Administration | Seraph, The Alchemist', robots: { index: false, follow: false } };
export default async function AdminPage({ searchParams }: { searchParams: Promise<{ error?: string; saved?: string }> }) {
  const { client, user } = await requireAccount('/admin');
  const { data, error } = await client.from('admin_memberships').select('user_id').eq('user_id', user.id).maybeSingle();
  if (error || !data) notFound();
  const params = await searchParams;
  const [profilesResult, reviewsResult, requestsResult] = await Promise.all([(client as any).from('profiles').select('id, display_name').order('display_name'), (client as any).from('reviews').select('id, customer_id, service_instance_id, status, created_at').eq('status', 'pending').order('created_at', { ascending: true }), (client as any).from('service_requests').select('id, customer_id, service_title, payment_method, payment_reference, contact_email, contact_phone, preferred_date, preferred_time, timezone, scheduled_at, status, note, admin_note, created_at').order('created_at', { ascending: true })]);
  const pendingReviews = reviewsResult.data ?? [];
  const revisionsResult = pendingReviews.length ? await (client as any).from('review_revisions').select('id, review_id, body, created_at').in('review_id', pendingReviews.map((r: any) => r.id)).order('created_at', { ascending: false }) : { data: [] };
  return <section className="account-page"><div className="account-panel"><p className="eyebrow">Sanctuary administration</p><h1>Welcome, Seraph</h1><p>Your administrator access is confirmed.</p>{params.error && <p role="alert" className="account-notice">The requested administration action could not be completed.</p>}{params.saved && <p role="status" className="account-notice">Saved.</p>}
    <div className="account-next"><h2>Verify a completed service</h2><form action={addServiceInstance} className="account-form"><label htmlFor="customer-id">Customer</label><select id="customer-id" name="customer_id" required><option value="">Choose a member</option>{(profilesResult.data ?? []).map((p: any) => <option value={p.id} key={p.id}>{p.display_name} ({p.id.slice(0, 8)})</option>)}</select><label htmlFor="service-slug">Published offering</label><select id="service-slug" name="service_slug" required><option value="">Choose an offering</option>{services.map(s => <option value={s.slug} key={s.slug}>{s.title}</option>)}</select><label htmlFor="completed-at">Completed on</label><input id="completed-at" name="completed_at" type="date" required /><SubmitButton pendingLabel="Saving…">Confirm service</SubmitButton></form></div>
    <div className="account-next"><h2>Scheduling queue</h2><p className="account-fine-print">Review payment and contact details, then set a time or update the request status.</p>{requestsResult.error ? <p role="alert">Apply the scheduling migration if this queue cannot be loaded.</p> : requestsResult.data?.length ? requestsResult.data.map((r: any) => <article className="review-entry" key={r.id}><h3>{r.service_title}</h3><p><strong>Contact:</strong> {r.contact_email ?? 'Email unavailable'}{r.contact_phone && ` · ${r.contact_phone}`}</p><p><strong>Payment:</strong> {r.payment_method} · {r.payment_reference}</p><p><strong>Preferred:</strong> {r.preferred_date ?? 'No date'}{r.preferred_time ? ` at ${r.preferred_time}` : ''} ({r.timezone ?? 'America/Chicago'})</p>{r.note && <p><strong>Note:</strong> {r.note}</p>}<form action={updateServiceRequest} className="account-form"><input type="hidden" name="request_id" value={r.id} /><label htmlFor={`request-status-${r.id}`}>Status</label><select id={`request-status-${r.id}`} name="status" defaultValue={r.status}><option value="pending">Pending</option><option value="contacted">Contacted</option><option value="scheduled">Scheduled</option><option value="completed">Completed</option><option value="canceled">Canceled</option><option value="declined">Declined</option></select><label htmlFor={`scheduled-date-${r.id}`}>Scheduled date</label><input id={`scheduled-date-${r.id}`} name="scheduled_date" type="date" defaultValue={r.scheduled_at ? new Date(r.scheduled_at).toISOString().slice(0, 10) : ''} /><label htmlFor={`scheduled-time-${r.id}`}>Scheduled time</label><input id={`scheduled-time-${r.id}`} name="scheduled_time" type="time" defaultValue={r.scheduled_at ? new Date(r.scheduled_at).toISOString().slice(11, 16) : ''} /><label htmlFor={`request-timezone-${r.id}`}>Timezone</label><input id={`request-timezone-${r.id}`} name="timezone" defaultValue={r.timezone ?? 'America/Chicago'} maxLength={80} /><label htmlFor={`admin-note-${r.id}`}>Admin note</label><textarea id={`admin-note-${r.id}`} name="admin_note" defaultValue={r.admin_note ?? ''} maxLength={1000} /><SubmitButton pendingLabel="Saving…">Save request</SubmitButton></form></article>) : <p>No service requests yet.</p>}</div>
    <div className="account-next"><h2>Testimonies awaiting review</h2>{reviewsResult.error ? <p role="alert">The review queue could not be loaded.</p> : pendingReviews.length ? pendingReviews.map((review: any) => { const revision = (revisionsResult.data ?? []).find((item: any) => item.review_id === review.id); return <article className="review-entry" key={review.id}><h3>Pending testimony</h3><p>{revision?.body ?? 'Revision unavailable'}</p><form action={moderateReview} className="account-links"><input type="hidden" name="review_id" value={review.id} /><input type="hidden" name="revision_id" value={revision?.id ?? ''} /><button name="decision" value="approved" type="submit">Publish</button><button name="decision" value="rejected" type="submit">Reject</button></form></article> }) : <p>No pending testimonies.</p>}</div>
    <div className="account-links"><Link href="/account">Return to my account</Link></div>
  </div></section>;
}
